/*
 그룹별 조건에 맞는 식당 목록 출력하기
 https://school.programmers.co.kr/learn/courses/30/lessons/131124
 */

-- 최대 리뷰 개수가 동일한 사용자가 여러 명인 경우 답안
SELECT M.MEMBER_NAME AS MEMBER_NAME,
       R.REVIEW_TEXT AS REVIEW_TEXT,
       R.REVIEW_DATE AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
  ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT R.MEMBER_ID AS MEMBER_ID
    FROM REST_REVIEW R
    GROUP BY R.MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)
        FROM (
                 SELECT COUNT(*) AS CNT
                 FROM REST_REVIEW
                 GROUP BY MEMBER_ID
             ) T
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT


-- 프로그래머스 모범답안
SELECT M.MEMBER_NAME AS MEMBER_NAME,
       R.REVIEW_TEXT AS REVIEW_TEXT,
       R.REVIEW_DATE AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
  ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
    )
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;