/*
 5월 식품들의 총매출 조회하기
 https://school.programmers.co.kr/learn/courses/30/lessons/131117
 */
SELECT P.PRODUCT_ID AS PRODUCT_ID,
       P.PRODUCT_NAME AS PRODUCT_NAME,
       P.PRICE * O.SALES AS TOTAL_SALES
FROM FOOD_PRODUCT P
         JOIN (
    SELECT PRODUCT_ID, PRODUCE_DATE, SUM(AMOUNT) AS SALES
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022
      AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) O
              ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID